### ISSUE TITLE
Mounting squashfs image via b2_fuse causes entire file download

### ISSUE THREAD

**Issue by szycha76** [sondree/b2_fuse#51]
Hello @sondree!

Thanks for your excellent work.

I'm trying to mount a squashfs image from b2 bucket mounted with b2_fuse, but this makes b2_fuse to download entire image. I thought that would not be necessary since implementation of 'range' parameter to avoid this.

I mount image that is 186 MiB long, but I intend to move my entire archive of half of my life (just under 1 TiB in size), mount over b2_fuse, and... (put anything here).

This would solve many issues with lack of attributes / timestamp support, only 1000 items returning in file list etc. This might in turn boost sales of B2 product to variety of new customers / integrators I guess.

But there is no point in mounting 1 TiB image if it requires prior download to one's desktop / laptop / mobile phone, right?

Thanks again. Stay safe.
Marcin.

**Comment by falense** [comment]
Hello Marcin!

It is true that with the range parameter you would not need to download the entire file normally. This is a feature I wanted to implement (but have not gotten around to) which would also enable streaming of media. Unfortunately, this is not the only hurdle to overcome. If you were able to mount your image (without downloading it entirely) you would still have to download a complete copy in order to modify the image. This is because file operations in B2 are atomic, they assume that the entire file is present and available at the time of upload.

I, like you, wanted to use B2 for general file storage and this was in part why I made B2Fuse. I agree that this feature would be very beneficial and a great use case for B2. Currently, however, there are no viable software options that would allow you to use B2 like described. 

From my research I have more or less concluded that in order to enable the type of use that I would like, essentially having B2 as a giant expandable NAS, you would have to implement a whole custom filesystem on top of B2 block storage. There is a number of reasons why this is hard, consistency is one. Things get even worse if you ever want to allow concurrent access to the data, as that would require additional safeguards as to not corrupt data. 

And finally, yes you are correct that it would be no point mounting a 1 TiB image. 

Best
Sondre

**Comment by szycha76** [comment]
Hi Sondre,

Thanks for quick answer.

Are we both talking about **read-only** squashfs filesystem images? When mounting r/o none of your worries apply, right?

All you'd need to take care of would be some smart LRU/MFU and the like cache persistence policy in order to get maximum performance when working with remote SquashFS images.

Best regards,
Marcin.

**Comment by falense** [comment]
Well I was under the assumption you wanted something RW, with read-only none of these apply yes. Still you would be better off with support for streaming/partial file downloads.

**Comment by falense** [comment]
Closing this as the feature of streaming/partial/sparse files is covered under another enhancement issue open (ref #25 )
