### ISSUE TITLE
Hangs on "list_buckets"

### ISSUE THREAD

**Issue by hopechannel** [sondree/b2_fuse#6]
This is an awesome looking tool, and I can't wait to use it. Thank you for creating it.

When attempting to mount B2, the software hangs at "list_buckets"

```
$ sudo python b2fuse.py /mnt/b2
2016-04-07 08:48:30,571:INFO:list_buckets
```

The bucket contains no files.

**Comment by CafeLungo** [comment]
This confused me at first, as well. I believe that is all there is to it. You can run it in the background or something, and then start using your mount-point. However, what I've seen is that the mount-point has no permissions at all-- I had to use the root account to even use it! I have not figured out how to get around that. For now I'm only "playing" with this to see what it is capable of, though. I hope someone can offer suggestion on this issue. I might even be using it wrong, too.

**Comment by falense** [comment]
Hi @hopechannel  and @CafeLungo!

There is really not much too it, the program is not designed to run as a daemon yet so it will block the terminal launching the program. @hopechannel you should have gotten some more output from the terminal, what happens if you try to create a file in the mounted folder?

Inherently, B2 does not support permissions. Some applications mimic permissions in B2 using extra file attributes (meta information stored with the file). B2Fuse does not care about permissions, so you should be able to access the files as any user. Have you checked that the mount point itself is accessible using a non-root user?

As for performance, the non-local version of this driver attempts to be as transparent as possible in exposing the B2 API. As such, what you are seeing in terms of delay for opening, deleting and listing files are the result of the the latency in B2 API calls. Typically a single call takes 1-2.5 second to execute. There has been significant work on speeding up this driver, in particular the file listings are cached at multiple levels (which should make exploring folders faster). There is only so much one can do about the performance when deleting files and opening (downloading). If I were to use the same approach as with B2Local (which use threads for upload, deletions and downloads), you would get inconsistent results. Especially, if you terminate the driver before it has completed all operations or try to access the bucket through another application (accessing the B2 API).

Future work includes making use of the recently released B2 large file upload, which may allow for large files to be handled better by downloading and uploading parts of a file at a time. 

Hope that answers some of you questions.

Sondre

**Comment by hopechannel** [comment]
Hi @sondree! Hey thanks a lot for the robust reply!
When I first tried running your program, it gave me errors when trying to access the mount.
I tried again after reading your your message, and it worked great.
The only thing I can surmise is that my initial attempt was only a few minutes after creating my B2 account and the new bucket.
I'm very excited about this software you're writing, and am looking forward to the new large file support. We're a television network with thousands of broadcast master video files that are over 20GB each.
